name: Python CI

on: 
    push:
      branches:
        - main

jobs:
    build:
       runs-on: ubuntu-latest

       steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
              python-version: '3.13'

        - name: Install Dependencies
          run: | 
               pip install requests

        - name: Run python script
          run: |
              python app.py


              
